version: '3'

services:

  api:
    image: henriquealbano/trabalho_microservicos_api2
    ports:
      - "3000:5000"
    depends_on:
      - mysql
    environment:
      MYSQL_USER: root
      MYSQL_DATABASE: 47bdt
      MYSQL_ROOT_PASSWORD: 47bdt
    deploy:
      replicas: 3
      #update_config:
      #  parallelism: 1
      #  delay: 10is
      mode: replicated
      restart_policy:
        condition: on-failure

  mysql:
    image: henriquealbano/trabalho_microservicos
    ports:
      - "3306:3306"
    volumes:
      - db-data:/var/lib/mysql
    environment:
      MYSQL_USER: root
      MYSQL_DATABASE: 47bdt
      MYSQL_ROOT_PASSWORD: 47bdt
    deploy:
      replicas: 1
      # resources:
      #   limits:
      #     cpus: "0.1"
      #     memory: 50M
      restart_policy:
        condition: on-failure

volumes:
  db-data:
